w9d3/cats_99/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :cats
end

w9d3/cats_99/app/models/cat.rb
class Cat < ApplicationRecord
  CAT_COLORS =  %w(red brown gray white black orange) 


    validates :birth_date, :color, :name, :sex, :description, presence: true
    validates :sex, inclusion: { in: %w(M F),
      message: "%{value} is not a valid size" }
    validates :color, inclusion: { 
      in: CAT_COLORS, message: "%{value} is not a valid color"
    }

  def age
    Date.today.year - self.birth_date.year
  end
end

w9d3/cats_99/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  skip_before_action :verify_authenticity_token
end

w9d3/cats_99/app/controllers/cats_controller.rb
class CatsController < ApplicationController

  def index
    @cat = Cat.all
    render :index
  end

  def show
    @cat = Cat.find(params[:id])
    render :show
  end

  def new
    render :new
  end

  def create
    @cat = Cat.new(cat_params)

    if @cat.save
      render :show
    else
      render json: @cat.errors.full_messages, status: 422
    end
    
  end

  def edit
    @cat = Cat.find(params[:id])
    render :edit

    if @cat.save
      render :show
    else
      render json: @cat.errors.full_messages, status: 422
    end
    
  end

  private

  def cat_params
    params.require(:cat).permit(:birth_date, :color, :name, :sex, :description)
  end

end

w9d3/cats_99/app/views/cats/edit.html.erb
<h1>Add a cat</h1>

<form action="<%= edit_cat_url %>" method="GET">

<label for="cat_name">Enter cat's name</label>
<input type="text" id="cat_name" name="cat[name]"><br>

<label for="Birth_date">Select cat's birth date</label>
<input type="date" id="Birth_date" name="cat[birth_date]"><br>

<label for="Color">Enter cat's color</label>
<select id="Color" name="cat[color]">
  <option> --Select a Color-- </option>
  <option value="red"> Red </option>
  <option value="brown"> Brown </option>
  <option value="gray"> Gray </option>
  <option value="white"> White </option>
  <option value="black"> Black </option>
  <option value="orange"> Orange </option>
</select><br>

<label for="Description">Enter cat's description</label>
<input type="text" id="Description" name="cat[description]"><br>


<div>
<label for="Sex">Enter cat's gender</label> 
<input type="radio" id="Sex" value="M" name="cat[sex]"> M
<input type="radio" id="Sex" value="F" name="cat[sex]"> F
</div><br>


  <input type="submit" value="Add your cat" >
  
  
</form>

w9d3/cats_99/app/views/cats/index.html.erb
<% @cat %>
<header>
<h1> Cats </h1>
<% @cat.each do |each_cat|%>

<ul>
  <li> <a href="<%= cat_url(id: each_cat.id) %>" > <%= each_cat.name %> </li>
</ul>

<%end%>

<p>
<a href="<%= new_cat_url %>"> Create a Cat here!
</p>
</header>

w9d3/cats_99/app/views/cats/new.html.erb
<h1>Add a cat</h1>

<form action="<%= cats_url %>" method="POST">

<label for="cat_name">Enter cat's name</label>
<input type="text" id="cat_name" name="cat[name]"><br>

<label for="Birth_date">Select cat's birth date</label>
<input type="date" id="Birth_date" name="cat[birth_date]"><br>

<label for="Color">Enter cat's color</label>
<select id="Color" name="cat[color]">
  <option> --Select a Color-- </option>
  <option value="red"> Red </option>
  <option value="brown"> Brown </option>
  <option value="gray"> Gray </option>
  <option value="white"> White </option>
  <option value="black"> Black </option>
  <option value="orange"> Orange </option>
</select><br>

<label for="Description">Enter cat's description</label>
<input type="text" id="Description" name="cat[description]"><br>


<div>
<label for="Sex">Enter cat's gender</label> 
<input type="radio" id="Sex" value="M" name="cat[sex]"> M
<input type="radio" id="Sex" value="F" name="cat[sex]"> F
</div><br>


  <input type="submit" value="Add your cat" >
  
  
</form>

w9d3/cats_99/app/views/cats/show.html.erb
<% @cat %>

<table>

  <caption> Cat Table </caption>

  <tr>
    <th scope="col">Birth Date</th>
    <th scope="col">Color</th>
    <th scope="col">Name</th>
    <th scope="col">Sex</th>
    <th scope="col">Description</th>
  </tr>

  <tr>
    <th> <%= @cat.birth_date %> </th>
    <th> <%= @cat.color %> </th>
    <th> <%= @cat.name %> </th>
    <th> <%= @cat.sex %> </th>
    <th> <%= @cat.description %> </th>
  </tr>

<p>
<a href="<%= edit_cat_url %>"> Edit a cat!
</p>
</table>

w9d3/cats_99/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cats99</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%#= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>